name: flutter-ci
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage
      - run: flutter build apk --release
      - run: flutter build web --release
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/app/outputs/**/*.apk
            build/web
